from __future__ import annotations

from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT_DIR / "data"
OUTPUT_DIR = DATA_DIR / "kci_output"

AREAS = {
    "language_education": {
        "name": "언어·교육 수요",
        "weight": 0.20,
        "role": "core",
        "rationale": "한국어 학습, 한국 유학, 한국학 개설처럼 시간과 비용을 투입하는 국가 선택 행동.",
    },
    "knowledge_innovation": {
        "name": "지식·혁신 역량",
        "weight": 0.18,
        "role": "core",
        "rationale": "특허, 연구 기여도, 혁신 순위로 나타나는 한국 지식생산 생태계의 국제적 위치.",
    },
    "medical_services": {
        "name": "의료·전문 서비스 신뢰",
        "weight": 0.14,
        "role": "core",
        "rationale": "외국인이 한국 의료를 직접 선택하고 지출하는 고비용 행동.",
    },
    "economy_investment": {
        "name": "경제·투자 매력",
        "weight": 0.14,
        "role": "core",
        "rationale": "외국인직접투자처럼 기업과 자본이 한국을 선택하는 행동.",
    },
    "foreign_media_digital": {
        "name": "외국 언론·정보 수요",
        "weight": 0.00,
        "role": "observational",
        "rationale": "외국 언론 노출량과 Wikipedia 조회처럼 한국 국가 자체에 대한 정보탐색 행동. 단순 보도량은 감성 보정 전까지 점수에서 제외한다.",
    },
    "democracy_governance": {
        "name": "민주주의·거버넌스 신뢰",
        "weight": 0.34,
        "role": "core",
        "rationale": "정치적 권리, 시민적 자유, 민주주의 작동 수준은 국가이미지의 제도적 신뢰 기반이다.",
    },
    "lifestyle_services": {
        "name": "생활문화 서비스 소비",
        "weight": 0.00,
        "role": "appendix",
        "rationale": "수출액이 아니라 해외 식당 방문, 인식, 외식 서비스 선택에 나타나는 생활문화 접촉.",
    },
}

EXCLUDED_VARIABLES = [
    "K-pop",
    "K-drama",
    "K-video",
    "K-game",
    "K-webtoon",
    "K-fashion",
    "K-beauty",
    "K-tourism",
    "YouTube views",
    "Reddit mentions/subscribers",
    "KF Hallyu status API",
    "K-Food exports",
]

INDICATORS = {
    "topik_total": {
        "area": "language_education",
        "name": "TOPIK 국내외 총 응시자",
        "unit": "persons",
        "direction": "positive",
        "source": "NIIE/data.go.kr; kci_behavioral_indicators.docx Table 1",
        "series": {2020: 218869, 2021: 330000, 2022: 360000, 2023: 420000, 2024: 490000, 2025: 553237},
    },
    "sejong_students": {
        "area": "language_education",
        "name": "세종학당 수강생",
        "unit": "persons",
        "direction": "positive",
        "source": "Sejong Institute Foundation/data.go.kr; document Table 1",
        "series": {2020: 101675, 2021: 138425, 2022: 178973, 2023: 216226, 2024: 210374, 2025: 239020},
    },
    "international_students": {
        "area": "language_education",
        "name": "한국 내 외국인 유학생",
        "unit": "persons",
        "direction": "positive",
        "source": "MOE/KEDI, Ministry of Justice; document Table 5",
        "series": {2020: 153695, 2021: 155281, 2022: 166892, 2023: 226507, 2024: 263775, 2025: 305329},
    },
    "korean_university_programs": {
        "area": "language_education",
        "name": "해외 한국어 교육기관 수",
        "unit": "institutions",
        "direction": "positive",
        "source": "KF/MCST; document Table 4. 2025 value includes primary/secondary schools, not universities only.",
        "series": {2017: 1300, 2021: 1600, 2024: 1800, 2025: 2777},
    },
    "pct_applications": {
        "area": "knowledge_innovation",
        "name": "WIPO PCT 국제 특허 출원",
        "unit": "applications",
        "direction": "positive",
        "source": "WIPO PCT Yearly Review; document Table 6",
        "series": {2018: 17000, 2020: 20000, 2022: 22000, 2023: 22288, 2024: 23851},
    },
    "gii_rank": {
        "area": "knowledge_innovation",
        "name": "WIPO 글로벌 혁신지수 순위",
        "unit": "rank",
        "direction": "rank",
        "rank_max": 30,
        "source": "WIPO GII; document Table 8",
        "series": {2019: 11, 2021: 5, 2022: 6, 2023: 10, 2024: 6, 2025: 4},
    },
    "nature_rank": {
        "area": "knowledge_innovation",
        "name": "Nature Index 종합 순위",
        "unit": "rank",
        "direction": "rank",
        "rank_max": 30,
        "source": "Nature Index 2026; document Table 7",
        "series": {2026: 7},
    },
    "foreign_patients": {
        "area": "medical_services",
        "name": "외국인 환자 수",
        "unit": "persons",
        "direction": "positive",
        "source": "MOHW/Medical Korea; document Table 9",
        "series": {2019: 497000, 2020: 146000, 2021: 146000, 2022: 248000, 2023: 610000, 2024: 1170467},
    },
    "medical_spending_krw": {
        "area": "medical_services",
        "name": "외국인 환자 의료 지출",
        "unit": "KRW 100m",
        "direction": "positive",
        "source": "MOHW/Yanolja Research; document Table 10",
        "series": {2019: 4091, 2024: 12401},
    },
    "fdi_inflow_usd_m": {
        "area": "economy_investment",
        "name": "FDI 유입액",
        "unit": "USD million",
        "direction": "positive",
        "source": "UNCTAD/World Bank; document Table 11 plus API refresh when available",
        "series": {2020: 8765, 2021: 22060, 2022: 25045, 2023: 19042, 2024: 15226},
    },
    "foreign_media_coverage": {
        "area": "foreign_media_digital",
        "name": "외국 언론의 한국 보도량",
        "unit": "articles, last 30 days",
        "direction": "positive",
        "score_included": False,
        "source": "GDELT 2.1 DOC API, English-language global news query for South Korea/Korea",
        "series": {},
    },
    "foreign_media_annualized": {
        "area": "foreign_media_digital",
        "name": "외국 언론 한국 보도량 연환산 추정치",
        "unit": "annualized articles",
        "direction": "positive",
        "score_included": False,
        "source": "Annualized estimate from the latest 30-day foreign media exposure sample.",
        "series": {},
    },
    "foreign_media_positivity": {
        "area": "foreign_media_digital",
        "name": "외국 언론 한국 보도 긍정지수",
        "unit": "0-100 headline positivity index",
        "direction": "bounded",
        "scale_min": 0,
        "scale_max": 100,
        "score_included": False,
        "source": "Google News RSS headline/description lexicon sentiment. Observational until full article NLP is added.",
        "series": {},
    },
    "wikimedia_pageviews": {
        "area": "foreign_media_digital",
        "name": "영문 Wikipedia 한국 문서 조회",
        "unit": "pageviews, latest full month",
        "direction": "positive",
        "score_included": False,
        "source": "Wikimedia REST API, en.wikipedia South_Korea pageviews",
        "series": {},
    },
    "google_trends_korea": {
        "area": "foreign_media_digital",
        "name": "Google Trends 'South Korea' 관심도",
        "unit": "index",
        "direction": "positive",
        "source": "Google Trends API/manual export; document section E-2",
        "series": {},
        "status": "connector_required",
    },
    "freedom_house_total": {
        "area": "democracy_governance",
        "name": "Freedom House 자유도 총점",
        "unit": "0-100 score",
        "direction": "bounded",
        "scale_min": 0,
        "scale_max": 100,
        "source": "Freedom House, Freedom in the World country rankings. South Korea latest score 83/100; 2025 country report score 81/100.",
        "series": {2025: 81, 2026: 83},
    },
    "freedom_house_political_rights": {
        "area": "democracy_governance",
        "name": "Freedom House 정치적 권리",
        "unit": "0-40 score",
        "direction": "bounded",
        "scale_min": 0,
        "scale_max": 40,
        "source": "Freedom House, Freedom in the World country rankings. South Korea latest political rights score 33/40; 2025 report 32/40.",
        "series": {2025: 32, 2026: 33},
    },
    "freedom_house_civil_liberties": {
        "area": "democracy_governance",
        "name": "Freedom House 시민적 자유",
        "unit": "0-60 score",
        "direction": "bounded",
        "scale_min": 0,
        "scale_max": 60,
        "source": "Freedom House, Freedom in the World country rankings. South Korea latest civil liberties score 50/60; 2025 report 49/60.",
        "series": {2025: 49, 2026: 50},
    },
    "korean_restaurant_chains": {
        "area": "lifestyle_services",
        "name": "해외 한국 외식기업 매장 수",
        "unit": "stores",
        "direction": "positive",
        "source": "MAFRA/aT overseas restaurant company survey; document Table 13",
        "series": {2020: 3722, 2023: 4382, 2025: 4644},
    },
    "korean_food_awareness": {
        "area": "lifestyle_services",
        "name": "해외 한국 음식 인지도",
        "unit": "percent",
        "direction": "bounded",
        "scale_min": 0,
        "scale_max": 100,
        "source": "MAFRA/KFPI 2025 overseas Korean food consumer survey; document Table 15",
        "series": {2025: 68.6},
    },
    "korean_food_satisfaction": {
        "area": "lifestyle_services",
        "name": "해외 한국 음식 만족도",
        "unit": "percent",
        "direction": "bounded",
        "scale_min": 0,
        "scale_max": 100,
        "source": "MAFRA/KFPI 2025 overseas Korean food consumer survey; document Table 15",
        "series": {2025: 94.2},
    },
}
